"""Petrochemical KA seed data from public authoritative sources."""

from __future__ import annotations

from typing import Any


KNOWLEDGE_BASE_PATH = "/Users/edmund/Documents/施耐德电气项目工作模式/施耐德电气研修院知识库.md"
SWITCHGEAR_COURSE_KNOWLEDGE_BASE_PATH = "/Users/edmund/Documents/施耐德电气项目工作模式/盘厂大客户洞察课程知识库.md"


PETROCHEM_TAGGING_SOURCES: list[dict[str, str]] = [
    {
        "id": "KB1",
        "title": "施耐德电气研修院知识库",
        "publisher": "用户提供/研修院知识库",
        "date": "2026-05-31",
        "url": KNOWLEDGE_BASE_PATH,
        "purpose": "项目打标、AOO2阶段、三层两闭环和企业洞察方法",
    },
    {
        "id": "KB2",
        "title": "盘厂企业洞察课程知识库",
        "publisher": "用户整理/云学堂与研修院内部课程",
        "date": "2026-06-01",
        "url": SWITCHGEAR_COURSE_KNOWLEDGE_BASE_PATH,
        "purpose": "盘厂企业洞察课程证据、9大模块调用矩阵、AOO2阶段、供应链交付和企业问诊卡",
    },
    {
        "id": "SE1",
        "title": "EcoStruxure Power Distribution",
        "publisher": "Schneider Electric",
        "date": "访问日期：2026-05-31",
        "url": "https://www.se.com/ww/en/work/campaign/innovation/power-distribution/",
        "purpose": "智能配电三层架构、互联互通产品、边缘控制、应用分析与服务",
    },
    {
        "id": "SE2",
        "title": "EcoStruxure Power Monitoring Expert 电能管理系统",
        "publisher": "Schneider Electric 中国",
        "date": "访问日期：2026-05-31",
        "url": "https://www.schneider-electric.cn/zh/product-range/65404-ecostruxure-power-monitoring-expert-%E7%94%B5%E8%83%BD%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F/",
        "purpose": "电能监控、能源效率、ISO 50001/50002/50006、审计与可靠性分析",
    },
    {
        "id": "SE3",
        "title": "EcoStruxure Power Operation",
        "publisher": "Schneider Electric",
        "date": "访问日期：2026-05-31",
        "url": "https://www.se.com/us/en/product-range/65405-ecostruxure-power-operation/",
        "purpose": "关键电力SCADA、实时监控、告警、开放通讯与业务连续性",
    },
    {
        "id": "SE4",
        "title": "EcoStruxure Power and Process for Oil, Gas and Petrochemicals",
        "publisher": "Schneider Electric",
        "date": "访问日期：2026-05-31",
        "url": "https://www.se.com/ww/en/work/solutions/for-business/oil-and-gas/power-and-process/",
        "purpose": "油气化工行业电力与过程方案、降碳、安全稳定和效率提升",
    },
    {
        "id": "SE5",
        "title": "BlokSeT MB low voltage switchboards enhance safety, reliability and connectivity",
        "publisher": "Schneider Electric",
        "date": "2021-10-26",
        "url": "https://www.se.com/ww/en/about-us/newsroom/news/press-releases/Schneider-Electric%E2%80%99s-nextgeneration-BlokSeT-MB-low-voltage-switchboards-enhance-the-safety-reliability-and-connectivity-of-innovative-power-distribution-and-motor-control-6176c872465664248212b264",
        "purpose": "BlokSeT MB、iPMCC、实时热监测、弧光防护、预测维护和低压/MCC可靠性证据",
    },
    {
        "id": "SE6",
        "title": "EcoStruxure Power Commission",
        "publisher": "Schneider Electric",
        "date": "访问日期：2026-06-02",
        "url": "https://www.se.com/sg/en/work/products/product-launch/ecostruxure-power-commission/",
        "purpose": "低压断路器和数字化配电柜配置、测试、调试、报告与维护工具",
    },
    {
        "id": "SE7",
        "title": "Digital services for improved uptime and efficiency",
        "publisher": "Schneider Electric",
        "date": "访问日期：2026-06-02",
        "url": "https://www.se.com/ww/en/work/services/digital-services/",
        "purpose": "预测性分析、AI、远程监控、Connected Services Hub、资产健康和运行效率服务",
    },
    {
        "id": "SE8",
        "title": "EcoStruxure Power Build Medium Voltage",
        "publisher": "Schneider Electric",
        "date": "访问日期：2026-06-02",
        "url": "https://www.se.com/ww/en/work/products/product-launch/ecoreal-mv/",
        "purpose": "面向盘厂的中压开关柜配置、报价、SLD、BOM、技术规格和订货文件工具",
    },
    {
        "id": "ISO1",
        "title": "ISO 50001 Energy Management Systems",
        "publisher": "International Organization for Standardization",
        "date": "公开资料",
        "url": "https://www.iso.org/files/live/sites/isoorg/files/store/en/PUB100400.pdf",
        "purpose": "能源管理体系、能效持续改进和能源绩效证据",
    },
]


PETROCHEM_KA_DATA: dict[str, dict[str, Any]] = {
    "中国石化": {
        "aliases": ["中国石化", "中石化", "sinopec"],
        "profile": {
            "short_name": "中国石化",
            "account_type": "央企能源化工一体化KA",
            "relationship": "炼油、化工、销售网络和新能源转型并重的战略型终端客户",
            "opportunity_level": "高",
            "risk_level": "中高",
            "recommended_focus": "炼化基地电气可靠性、化工装置安全供电、能效管理和存量改造",
        },
        "facts": {
            "entity": "中国石油化工股份有限公司 / 中国石油化工集团有限公司",
            "nature": "中央企业控股、A/H股上市能源化工集团",
            "ownership": "中国石化集团控股，具体股权以年度报告披露为准",
            "business": "油气勘探开发、炼油、成品油营销分销、化工产品生产销售、新能源和新材料",
            "products": "成品油、基础化工、合成树脂、合成纤维、合成橡胶、精细化工与新能源相关产品",
            "scale": "中国大型炼化与化工生产商，拥有全国性炼化基地、油品销售网络和化工销售体系",
            "finance": "2025年年报披露炼油板块经营收益改善，化工板块受行业新增产能与毛利压力影响仍承压",
            "projects": "镇海、茂名、齐鲁、九江、上海石化、扬子等炼化/化工基地，以及化工销售一体化平台",
            "market": "面向交通燃料、工业客户、化工材料、聚合物、新能源材料和终端零售市场",
            "strategy": "向世界领先洁净能源化工公司转型，推进高端材料、新能源、数字化和绿色低碳",
            "digital": "大型炼化企业已推进智能工厂、装置实时优化、AI应用和经营数字化，具体厂区系统需逐点核验",
            "green": "可持续发展报告披露ESG、低碳、节能减排和新能源布局，化工低景气与碳约束并存",
            "risk": "燃油需求结构变化、化工产能过剩、油价波动、装置安全环保和大型基地连续生产风险",
        },
        "sources": [
            {"id": "SP1", "title": "中国石化2025 Annual Report", "publisher": "中国石化集团官网/公告", "date": "2026-03", "url": "https://www.sinopecgroup.com/u/cms/jtyw/202603/22203315gxqf.pdf", "purpose": "年度报告、业务结构、治理与财务"},
            {"id": "SP2", "title": "中国石化2025年度业绩报道", "publisher": "新华社", "date": "2026-03-25", "url": "https://www.news.cn/finance/20260325/fd0b509bae524c9abeab6d5775240b4e/c.html", "purpose": "经营表现、板块趋势和行业压力"},
            {"id": "SP3", "title": "中国石化化工销售有限公司企业介绍", "publisher": "中国石化官网", "date": "访问日期：2026-05-30", "url": "https://hgxs.sinopec.com/hgxs/about_us/instro/", "purpose": "化工销售、客户资源和市场覆盖"},
        ],
    },
    "中国石油": {
        "aliases": ["中国石油", "中石油", "petrochina", "cnpc"],
        "profile": {
            "short_name": "中国石油",
            "account_type": "央企油气炼化与销售KA",
            "relationship": "油气上游、炼化、新能源和销售一体化的战略终端客户",
            "opportunity_level": "高",
            "risk_level": "中",
            "recommended_focus": "炼化基地配电升级、油气田电气安全、管网站场供电可靠性和低碳园区",
        },
        "facts": {
            "entity": "中国石油天然气股份有限公司 / 中国石油天然气集团有限公司",
            "nature": "中央企业控股、A/H股上市综合性油气公司",
            "ownership": "中国石油集团控股，具体股权以年度报告披露为准",
            "business": "油气勘探开发、炼油化工、新材料、成品油销售、天然气销售、新能源和工程技术服务",
            "products": "原油、天然气、成品油、基础化工、合成树脂、化肥、炼化新材料及能源服务",
            "scale": "国内油气产量和天然气供应能力领先，拥有上游油气田、炼化基地和全国销售网络",
            "finance": "2025年年报披露营业收入约2.86万亿元、归母净利润约1573亿元，油气产量再创新高",
            "projects": "长庆、塔里木、大庆、西南等油气田，广东石化、云南石化、吉林石化等炼化与转型项目",
            "market": "油气供应、成品油销售、天然气城市燃气/工业客户、化工材料和新能源应用",
            "strategy": "增储上产、炼化转型升级、天然气与新能源协同、数字化油田和绿色低碳发展",
            "digital": "油气田、管道、炼化和销售体系具备数字化场景，具体厂站系统需客户访谈确认",
            "green": "社会责任报告披露能源转型、绿色低碳、CCUS和新能源业务布局",
            "risk": "油价波动、天然气保供、炼化毛利、工程项目交付、安全环保和站场可靠供电风险",
        },
        "sources": [
            {"id": "CNPC1", "title": "中国石油2025年度报告", "publisher": "巨潮资讯/上市公司公告", "date": "2026-03-30", "url": "https://static.cninfo.com.cn/finalpage/2026-03-30/1225049376.PDF", "purpose": "年度报告、财务和业务结构"},
            {"id": "CNPC2", "title": "中国石油2025年社会责任报告", "publisher": "中国石油集团", "date": "2026-05", "url": "https://www.cnpc.com.cn/cnpc/lncbw/202605/955e5fbc218b4260971e26d8048675e3/files/ff7429675bf24ac08cab9e14354d53ed.pdf", "purpose": "ESG、绿色低碳、社会责任"},
            {"id": "CNPC3", "title": "中国石油2025年油气产量再创历史新高", "publisher": "中国经济网/证券日报", "date": "2026-03-30", "url": "https://www.ce.cn/cysc/newmain/yc/jsxw/202603/t20260330_2864727.shtml", "purpose": "经营趋势和产量线索"},
        ],
    },
    "中国海油/中海壳牌": {
        "aliases": ["中国海油", "中海壳牌", "cnooc", "shell", "cspc"],
        "profile": {
            "short_name": "中国海油/中海壳牌",
            "account_type": "央企海上油气与外资合资炼化KA",
            "relationship": "海上油气央企与惠州大亚湾合资化工基地并行的复合型客户",
            "opportunity_level": "高",
            "risk_level": "中",
            "recommended_focus": "海上平台供电、惠州乙烯扩建、配电可靠性、能效与安环合规",
        },
        "facts": {
            "entity": "中国海洋石油有限公司 / 中海壳牌石油化工有限公司",
            "nature": "中央企业上市油气公司 + CNOOC/Shell 50:50合资石化公司",
            "ownership": "中国海油体系；中海壳牌由壳牌南海与中海油石化投资等股东方持有",
            "business": "海上油气勘探开发生产、天然气与新能源；中海壳牌从事乙烯及下游石化产品",
            "products": "原油、天然气、乙烯、聚烯烃、聚碳酸酯及相关化工产品",
            "scale": "中国最大海上油气生产商之一，惠州大亚湾中海壳牌为大型石化合资基地",
            "finance": "中国海油2025年度报告披露储量和产量创新高，盈利保持韧性；合资公司财务需单独访谈/工商材料补充",
            "projects": "海上油气项目、惠州中海壳牌三期乙烯、聚碳酸酯及大亚湾化工扩建项目",
            "market": "油气供应、海上工程、华南化工材料、汽车电子、包装和工业材料客户",
            "strategy": "增储上产、技术创新、绿色发展；惠州基地继续扩建高端化工材料能力",
            "digital": "海上平台、化工园区和大型连续生产装置数字化需求明显，具体系统需调研",
            "green": "中国海油推进低碳园区、海上风电、CCUS；中海壳牌扩建需满足安环和低碳要求",
            "risk": "海上作业安全、台风环境、合资决策链、化工扩建交付和安全环保合规风险",
        },
        "sources": [
            {"id": "CNOOC1", "title": "中国海油有限公司年度报告页面", "publisher": "中国海油有限公司", "date": "2026-04", "url": "https://ltd.cnooc.com.cn/english/investorrelations/reports/annualreport/", "purpose": "年度报告、储量产量和财务"},
            {"id": "CNOOC2", "title": "中国海油集团公司概览", "publisher": "中国海洋石油集团", "date": "访问日期：2026-05-30", "url": "https://www.cnooc.com.cn/English/aboutus_322/companyoverview/", "purpose": "集团定位和业务概况"},
            {"id": "CSPC1", "title": "CSPC expansion in China", "publisher": "Shell Global", "date": "2025", "url": "https://www.shell.com/news-and-insights/newsroom/news-and-media-releases/2025/cspc-a-shell-cnooc-jv-invests-in-petrochemical-complex-expansion-in-china.html", "purpose": "中海壳牌扩建、股权与项目"},
            {"id": "CSPC2", "title": "中海壳牌惠州三期乙烯项目开工", "publisher": "新华社", "date": "2025-01-15", "url": "https://www.news.cn/20250115/f8d01ae061314307978d87286fa8b219/c.html", "purpose": "三期乙烯和聚碳酸酯项目规模"},
        ],
    },
    "巴斯夫湛江": {
        "aliases": ["巴斯夫湛江", "巴斯夫", "basf", "zhanjiang"],
        "profile": {
            "short_name": "巴斯夫湛江",
            "account_type": "外资独资世界级一体化基地KA",
            "relationship": "新投产世界级化工基地，电气可靠性、能效和数字化标准要求高",
            "opportunity_level": "高",
            "risk_level": "中",
            "recommended_focus": "乙烯裂解与下游装置供电可靠性、数字化配电、能效和备件服务",
        },
        "facts": {
            "entity": "巴斯夫一体化基地（广东）有限公司 / BASF Zhanjiang Verbund site",
            "nature": "外商独资重化工项目运营主体",
            "ownership": "巴斯夫集团全资子公司运营",
            "business": "世界级一体化化工生产基地，覆盖基础化学品、中间体、工程塑料、TPU等",
            "products": "乙烯及下游化学品、工程塑料、热塑性聚氨酯、特种化学品和中间体",
            "scale": "巴斯夫全球第三大一体化基地，投资约100亿美元，员工超过2000人",
            "finance": "单体财务未公开，项目以巴斯夫全球投资和湛江基地投产进度为主线评估",
            "projects": "湛江一体化基地、乙烯联合装置、工程塑料、TPU、液散码头与配套公辅设施",
            "market": "服务华南和亚洲汽车、电子、消费品、包装、工业材料等增长行业",
            "strategy": "打造巴斯夫在中国的化工生产旗舰，支持创新、低碳和本地化供应",
            "digital": "新建基地具备高标准自动化、数字化运维和能源管理需求",
            "green": "外资独资重化工项目高度重视绿色低碳、安环合规和海关/港口协同",
            "risk": "新基地爬坡、连续生产稳定性、进口设备维保、安环合规和供应链本地化风险",
        },
        "sources": [
            {"id": "BASF1", "title": "巴斯夫湛江一体化基地", "publisher": "巴斯夫官网", "date": "访问日期：2026-05-30", "url": "https://www.basf.com/cn/zh/who-we-are/organization/key-production-sites/guangdong", "purpose": "基地概况、投产和业务范围"},
            {"id": "BASF2", "title": "巴斯夫全面启用湛江一体化基地", "publisher": "巴斯夫官网", "date": "2026-03-26", "url": "https://www.basf.com/basf/www/cn/zh/media/news-releases/global/2026/03/apac-26-31", "purpose": "全面投产、员工、产品与战略"},
            {"id": "BASF3", "title": "湛江海关护航巴斯夫项目全面建成投产", "publisher": "湛江市人民政府", "date": "2026-03", "url": "https://www.zhanjiang.gov.cn/zwgk/zwzt/yshj/ysdt/content/post_2160826.html", "purpose": "政府侧项目进度、乙烯规模和配套码头"},
        ],
    },
    "埃克森美孚惠州": {
        "aliases": ["埃克森美孚惠州", "埃克森美孚", "exxonmobil", "惠州乙烯"],
        "profile": {
            "short_name": "埃克森美孚惠州",
            "account_type": "外资独资化工综合体KA",
            "relationship": "惠州大亚湾新投产化工综合体，聚烯烃与高端化工材料需求明确",
            "opportunity_level": "高",
            "risk_level": "中",
            "recommended_focus": "聚烯烃装置供配电、MCC/变频、能效监测、可靠性服务和备件",
        },
        "facts": {
            "entity": "埃克森美孚惠州乙烯项目 / Huizhou Chemical Complex",
            "nature": "外资独资大型石化项目",
            "ownership": "ExxonMobil在中国投资建设运营",
            "business": "乙烯裂解、聚乙烯、聚丙烯及高性能化工材料生产",
            "products": "聚乙烯、聚丙烯、高性能化学品和包装/汽车/工业材料",
            "scale": "位于惠州大亚湾石化区，官方披露聚乙烯/聚丙烯合计设计能力超过250万吨/年",
            "finance": "项目单体财务未公开，ExxonMobil全球披露中国世界级化工综合体投产和高价值产能扩张",
            "projects": "惠州乙烯一期、研发中心、未来扩建和大亚湾化工园协同",
            "market": "中国及亚太包装、汽车、消费品、工业材料和高端聚烯烃客户",
            "strategy": "扩大高价值化工产能和中国本地制造能力，提升亚太供应链响应",
            "digital": "新建世界级化工综合体具备高自动化、资产绩效管理和能源管理需求",
            "green": "项目需满足广东大亚湾高标准安全环保和绿色化工园区要求",
            "risk": "新装置爬坡、进口技术备件、安环、化工周期、二期审批和本地供应链风险",
        },
        "sources": [
            {"id": "XOM1", "title": "ExxonMobil China", "publisher": "ExxonMobil", "date": "访问日期：2026-05-30", "url": "https://corporate.exxonmobil.com/locations/china", "purpose": "在华业务和惠州投资"},
            {"id": "XOM2", "title": "ExxonMobil to invest in petrochemical complex in China", "publisher": "ExxonMobil", "date": "2021-11-08", "url": "https://corporate.exxonmobil.com/news/news-releases/2021/1108_exxonmobil-to-invest-in-petrochemical-complex-in-china", "purpose": "FID、产能和项目定位"},
            {"id": "XOM3", "title": "埃克森美孚惠州乙烯一期项目产出合格乙烯", "publisher": "广东省人民政府", "date": "2025-04-14", "url": "https://www.gd.gov.cn/gdywdt/tzdt/content/post_4696191.html", "purpose": "政府侧项目投产和园区定位"},
            {"id": "XOM4", "title": "ExxonMobil landmark chemical complex enters operation in China", "publisher": "新华社英文", "date": "2025-07-15", "url": "https://english.news.cn/20250715/0a946368d6f44429bc4da5bfa72a0e1d/c.html", "purpose": "投产节点和项目里程碑"},
        ],
    },
    "万华化学": {
        "aliases": ["万华化学", "wanhua"],
        "profile": {
            "short_name": "万华化学",
            "account_type": "全球化工新材料龙头KA",
            "relationship": "聚氨酯、石化、新材料与未来产业并进的高价值化工客户",
            "opportunity_level": "高",
            "risk_level": "中",
            "recommended_focus": "烟台/宁波/福建等基地电气升级、连续生产可靠性、能源管理和全球标准",
        },
        "facts": {
            "entity": "万华化学集团股份有限公司",
            "nature": "A股上市、全球化运营的化工新材料公司",
            "ownership": "具体股权以年度报告披露为准",
            "business": "聚氨酯、石化、精细化学品、新兴材料、未来产业五大产业集群",
            "products": "MDI、TDI、多元醇、丙烯酸及酯、聚烯烃、新材料、特种化学品",
            "scale": "拥有国内外十四大生产基地及工厂，七大研发中心，全球化销售和服务网络",
            "finance": "2025年营业收入2032.35亿元，归母净利润125.27亿元，收入增长但利润承压",
            "projects": "烟台、宁波、福建、四川、珠海、宁夏及海外基地，新材料和技改项目持续推进",
            "market": "建筑、汽车、家电、鞋材、涂料、电子、新能源和高端材料客户",
            "strategy": "从化工企业向化工+新能源转型，强化聚氨酯领先和新材料布局",
            "digital": "多基地连续生产和全球化运营带来DCS/MES/能源管理/预测维护需求",
            "green": "官网和年报披露绿色低碳、质量安全和创新驱动，危化品安全要求高",
            "risk": "化工价格周期、原料成本、海外运营、危化品安全、装置连续性和环保风险",
        },
        "sources": [
            {"id": "WH1", "title": "万华简介", "publisher": "万华化学官网", "date": "访问日期：2026-05-30", "url": "https://www.whchem.com/column/79/", "purpose": "公司定位、基地和产品线"},
            {"id": "WH2", "title": "万华化学2025年年度报告", "publisher": "巨潮资讯", "date": "2026-04-21", "url": "https://static.cninfo.com.cn/finalpage/2026-04-21/1225130793.PDF", "purpose": "年度报告、财务和业务"},
            {"id": "WH3", "title": "万华化学2025年业绩报道", "publisher": "新浪财经", "date": "2026-04-20", "url": "https://finance.sina.com.cn/stock/zqgd/2026-04-20/doc-inhvehiw6732640.shtml", "purpose": "财务数据和行业解读"},
        ],
    },
    "荣盛石化/浙石化": {
        "aliases": ["荣盛石化", "浙石化", "浙江石化", "rongsheng"],
        "profile": {
            "short_name": "荣盛石化/浙石化",
            "account_type": "民营炼化聚酯一体化KA",
            "relationship": "舟山炼化、芳烃、聚酯与新材料链条深度一体化的民营巨头",
            "opportunity_level": "高",
            "risk_level": "中高",
            "recommended_focus": "舟山炼化基地配电可靠性、储运码头、电能质量、碳管理和技改项目",
        },
        "facts": {
            "entity": "荣盛石化股份有限公司 / 浙江石油化工有限公司",
            "nature": "A股上市民营石化龙头，浙石化为其核心炼化平台",
            "ownership": "荣盛控股体系，具体股权以年度报告披露为准",
            "business": "油品、化工品、聚酯产品、新能源材料、高端聚烯烃、工程塑料等",
            "products": "PX、PTA、聚酯、聚烯烃、油品、工程塑料、新能源和特种材料",
            "scale": "七大生产基地，浙石化4000万吨/年炼化一体化项目支撑全球级芳烃/炼化能力",
            "finance": "2025年营业收入约3086.22亿元，归母净利润约8.48亿元，经营现金流改善",
            "projects": "浙江石化舟山绿色石化基地、聚酯和新材料基地、原油储备与码头储运项目",
            "market": "聚酯、化纤、包装、工程塑料、新能源材料、油品和化工品市场",
            "strategy": "从大炼化向高端化、新材料、低碳化和国际化协同升级",
            "digital": "超大型炼化和储运体系需要资产监控、能源管理、状态监测和电气健康管理",
            "green": "可持续发展报告披露环境、质量安全、责任采购和绿色低碳",
            "risk": "炼化价差、资产负债率、原油价格、地缘贸易、装置安全和环保合规风险",
        },
        "sources": [
            {"id": "RS1", "title": "荣盛石化官网", "publisher": "荣盛石化", "date": "访问日期：2026-05-30", "url": "https://www.cnrspc.com/", "purpose": "公司定位、业务和低碳转型"},
            {"id": "RS2", "title": "荣盛石化2025年年度报告", "publisher": "新浪财经公告镜像", "date": "2026-04", "url": "https://money.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12229348&stockid=002493", "purpose": "年度报告、财务和业务结构"},
            {"id": "RS3", "title": "荣盛石化2025年可持续发展报告", "publisher": "新浪财经公告镜像", "date": "2026-04", "url": "https://money.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12229336&stockid=002493", "purpose": "ESG、质量安全、责任采购"},
            {"id": "ZPC1", "title": "浙江石化4000万吨/年炼化一体化项目资料", "publisher": "浙江政务公开资料", "date": "公开资料", "url": "https://zjjcmspublic.oss-cn-hangzhou-zwynet-d01-a.internet.cloud.zj.gov.cn/jcms_files/jcms1/web2237/site/attach/0/05cf2be9d7e04c45ada8d3473ddd4b73.pdf", "purpose": "浙石化项目规模和基地线索"},
        ],
    },
    "恒力石化": {
        "aliases": ["恒力石化", "hengli"],
        "profile": {
            "short_name": "恒力石化",
            "account_type": "民营炼化聚酯一体化KA",
            "relationship": "大连炼化、PTA、聚酯和新材料链条一体化的重点客户",
            "opportunity_level": "高",
            "risk_level": "中高",
            "recommended_focus": "大连炼化基地可靠供电、电气安全、能效优化和政策风险应对",
        },
        "facts": {
            "entity": "恒力石化股份有限公司",
            "nature": "A股上市民营石化和聚酯龙头",
            "ownership": "恒力集团体系，具体股权以年度报告披露为准",
            "business": "炼化、石化、PTA、聚酯新材料、功能性薄膜和纤维产业链",
            "products": "成品油、芳烃、烯烃、PTA、聚酯、薄膜、工程塑料和新材料",
            "scale": "拥有大连长兴岛炼化基地和多地聚酯/新材料生产平台",
            "finance": "2025年营业收入约2009.86亿元、归母净利润约70.75亿元，炼化产销保持韧性",
            "projects": "大连炼化一体化基地、PTA和聚酯新材料项目、科技创新债相关技改投入",
            "market": "油品、化工品、聚酯、纤维、包装材料、新材料和海外客户",
            "strategy": "依托大化工平台推进高端新材料、全产业链协同和低碳转型",
            "digital": "炼化/聚酯连续生产对DCS/MES/能源管理和电气资产健康管理要求高",
            "green": "披露可持续发展报告，需关注安全环保、能源消耗和政策合规",
            "risk": "炼化周期、海外制裁/合规不确定性、油价波动、资产负债和装置安全风险",
        },
        "sources": [
            {"id": "HL1", "title": "恒力石化2025年度报告摘要", "publisher": "同花顺公告镜像", "date": "2026-04", "url": "https://notice.10jqka.com.cn/api/pdf/327ad30330785ea5_1776158340/%E6%81%92%E5%8A%9B%E7%9F%B3%E5%8C%96%EF%BC%9A%E6%81%92%E5%8A%9B%E7%9F%B3%E5%8C%962025%E5%B9%B4%E5%B9%B4%E5%BA%A6%E6%8A%A5%E5%91%8A%E6%91%98%E8%A6%81.pdf", "purpose": "年度报告摘要和财务"},
            {"id": "HL2", "title": "恒力石化2025年年报点评", "publisher": "新浪财经/券商研报", "date": "2026-04", "url": "https://stock.finance.sina.com.cn/stock/go.php/vReport_Show/kind/search/rptid/829735155878/index.phtml", "purpose": "业务趋势和财务解读"},
            {"id": "HL3", "title": "恒力石化2025年度可持续发展报告信息", "publisher": "中财网", "date": "2026-05", "url": "https://www.cfi.net.cn/p20260511000888.html", "purpose": "ESG与可持续发展线索"},
        ],
    },
    "东方盛虹/盛虹炼化": {
        "aliases": ["江苏东方盛虹股份有限公司", "江苏东方盛虹", "东方盛虹", "盛虹炼化", "盛虹石化", "斯尔邦", "shenghong"],
        "profile": {
            "short_name": "江苏东方盛虹股份有限公司 / 东方盛虹",
            "account_type": "盘厂KA/炼化新材料终端业主KA",
            "relationship": "连云港徐圩炼化新材料基地、盛虹炼化、斯尔邦石化和聚酯化纤多基地协同，是盘厂业务应按项目入口经营的基地型KA",
            "opportunity_level": "高",
            "risk_level": "中高",
            "recommended_focus": "盛虹炼化/斯尔邦/虹港/化纤基地的中低压柜、MCC、变频、电能质量、智能配电、能效管理、检修备件和服务框架",
        },
        "facts": {
            "entity": "江苏东方盛虹股份有限公司 / 盛虹炼化（连云港）有限公司",
            "nature": "A股上市民营能源化工与新材料企业，深圳证券交易所主板上市，股票代码000301",
            "ownership": "控股股东江苏盛虹科技股份有限公司直接持股43.24%；盛虹石化集团16.92%、盛虹（苏州）集团7.00%等为一致行动人；实际控制人为缪汉根、朱红梅夫妇",
            "business": "石化及化工新材料、聚酯化纤两大主业，构建炼化一体化、MTO、PDH、EVA/POE、丙烯腈、聚酯化纤和绿色低碳材料链条",
            "products": "1600万吨/年炼化一体化、280万吨/年PX、110万吨/年乙烯、240万吨/年MTO、70万吨/年PDH、104万吨/年丙烯腈、90万吨/年EVA、10万吨/年POE、34万吨/年MMA、约360万吨/年涤纶长丝及60万吨/年再生聚酯纤维",
            "scale": "连云港徐圩新区石化及新材料基地、苏州/宿迁聚酯化纤基地；2025年末在职员工27,878人，其中生产19,224人、技术4,862人、销售497人",
            "finance": "2025年营业收入1,255.87亿元，归母净利润1.34亿元，扣非净利润-5.43亿元，经营性现金流净额160.53亿元；2026年一季度营业收入320.22亿元、归母净利润14.32亿元、经营性现金流35.34亿元，盈利和现金流明显修复；资产负债率仍约81%",
            "projects": "盛虹炼化1600万吨/年炼化一体化项目、斯尔邦MTO/PDH/EVA/POE/丙烯腈、虹港PTA、虹威POSM及多元醇、石化港储、公辅/码头/储运、聚酯化纤、绿色低碳材料和10万吨/年POE工业化装置等项目",
            "market": "光伏胶膜、碳纤维、聚酯化纤、能源燃料、化工品、新能源材料、包装、工业材料和海外40余个国家/地区客户",
            "strategy": "围绕新能源材料、高性能新材料、低碳绿色产业推进“1+N”产业格局，2026年重点深化AI融合、高端化、绿色化、数智化和提质增效",
            "digital": "已上线盛虹流程工业智能大模型平台，推进集团级知识引擎、PDH核心装置操作导航、智能物料系统、法务智能助手、黑灯实验室、采购系统智能化升级和设备助手试点",
            "green": "盛虹炼化、斯尔邦、虹港、国望高科、芮邦科技等绿色工厂线索突出；拥有二氧化碳到聚酯纤维、废弃矿泉水瓶到聚酯纤维两条绿色产业链",
            "risk": "盈利从2025年低位到2026年一季度修复，但资产负债率仍高，原油/甲醇/丙烷价格和产品价差波动、安全环保监管、连续生产停机、项目付款信用和新材料装置爬坡仍是经营风险",
        },
        "sources": [
            {"id": "SH1", "title": "东方盛虹2025年年度报告", "publisher": "巨潮资讯/上市公司公告", "date": "2026-04-29", "url": "https://static.cninfo.com.cn/finalpage/2026-04-29/1225243361.PDF", "purpose": "年度报告、公司信息、股权、财务、产能、员工、智能工厂、风险和战略"},
            {"id": "SH2", "title": "关于我们-东方盛虹", "publisher": "东方盛虹官网", "date": "访问日期：2026-06-02", "url": "https://www.jsessh.com/zh/about/", "purpose": "官网公司简介、产业基地、绿色产业链、荣誉资质和业务定位"},
            {"id": "SH3", "title": "关于盛虹炼化（连云港）有限公司炼化一体化项目环境影响报告书的批复", "publisher": "生态环境部", "date": "2018-12-13", "url": "https://www.mee.gov.cn/xxgk2018/xxgk/xxgk11/201812/t20181213_684732.html", "purpose": "盛虹炼化1600万吨炼油、280万吨芳烃、110万吨乙烯、码头储运、公辅环保工程"},
            {"id": "SH4", "title": "横河电机为盛虹1600万吨/年炼化一体化项目提供解决方案", "publisher": "Yokogawa China", "date": "2022-05-23", "url": "https://www.yokogawa.com/cn/news/press-releases/2022/2022-05-23/", "purpose": "盛虹炼化自动化/控制系统供应商线索、项目投产和数字化运维场景"},
            {"id": "SH5", "title": "东方盛虹2025年业绩报道", "publisher": "新浪财经", "date": "2026-04-29", "url": "https://finance.sina.com.cn/stock/zqgd/2026-04-29/doc-inhwczny7926656.shtml?froms=ggmp", "purpose": "业绩和业务结构公开报道交叉验证"},
            {"id": "SH6", "title": "盛虹炼化（连云港）有限公司炼化产业介绍", "publisher": "东方盛虹官网", "date": "访问日期：2026-06-02", "url": "https://www.jsessh.com/lhcy/", "purpose": "盛虹炼化1600万吨项目、总投资、装置、码头仓储和项目定位"},
            {"id": "SH7", "title": "东方盛虹2026年一季度报告", "publisher": "上市公司公告/新浪财经镜像", "date": "2026-04-29", "url": "https://money.finance.sina.com.cn/corp/view/vCB_AllBulletinDetail.php?id=12266547&stockid=000301", "purpose": "2026年一季度营收、利润、现金流、资产和最新经营修复情况"},
            {"id": "SH8", "title": "东方盛虹：行业周期底部企稳 一季度业绩同比增长319.86%", "publisher": "证券时报", "date": "2026-04-28", "url": "https://www.stcn.com/article/detail/3853093.html", "purpose": "2025年报与2026年一季报业绩、行业底部企稳、产销和战略公开报道"},
            {"id": "SH9", "title": "盛虹石化10万吨/年POE项目投产", "publisher": "新浪财经/行业新闻", "date": "2025-09-04", "url": "https://finance.sina.com.cn/jjxw/2025-09-04/doc-infpimrm8716150.shtml?froms=ggmp", "purpose": "POE装置投产、光伏胶膜和高端新材料项目机会线索"},
            {"id": "SH10", "title": "Chemicals 50 2026 brand ranking", "publisher": "Brand Finance", "date": "2026-04-08", "url": "https://brandfinance.com/press-releases/rongsheng-petrochemical-cements-position-as-fifth-most-valuable-chemicals-brand-worldwide", "purpose": "东方盛虹位列全球化学化工品牌价值榜第24位及市场压力线索"},
        ],
    },
    "宝丰能源/卫星化学": {
        "aliases": ["宝丰能源", "卫星化学", "baofeng", "satellite chemical"],
        "profile": {
            "short_name": "宝丰能源/卫星化学",
            "account_type": "煤基/轻烃化工双KA",
            "relationship": "宝丰煤制烯烃与卫星轻烃一体化均是化工新材料重点客户",
            "opportunity_level": "中高",
            "risk_level": "中",
            "recommended_focus": "煤化工和轻烃化工基地供配电、MCC/变频、能效管理和扩产项目",
        },
        "facts": {
            "entity": "宁夏宝丰能源集团股份有限公司 / 卫星化学股份有限公司",
            "nature": "A股上市民营化工企业组合",
            "ownership": "宝丰能源、卫星化学均以各自年报股权为准",
            "business": "宝丰：煤炭采选、焦化、甲醇、烯烃、精细化工、新能源；卫星：C2/C3轻烃化工、丙烯酸及酯、高分子材料",
            "products": "烯烃、聚乙烯、聚丙烯、甲醇、焦化产品、丙烯酸及酯、SAP、高分子乳液和新材料",
            "scale": "宝丰内蒙古300万吨/年烯烃项目投产，卫星化学营收超460亿元并推进嘉兴/连云港基地",
            "finance": "宝丰能源2025年营收约480.38亿元、归母净利润约113.50亿元；卫星化学2025年营收超460亿元",
            "projects": "宝丰宁东/内蒙古煤制烯烃项目、卫星嘉兴丙烯酸和连云港轻烃一体化项目",
            "market": "聚烯烃、丙烯酸、包装、涂料、胶粘剂、卫生用品、新能源和化工材料客户",
            "strategy": "宝丰推进煤基新材料循环经济和新能源协同；卫星推进轻烃化工和高端材料",
            "digital": "扩产项目多、连续生产和能耗强度高，适合能源管理、配电监测和资产健康管理",
            "green": "宝丰强调煤炭清洁高效利用和新能源，卫星披露ESG报告并推进绿色化工",
            "risk": "煤价/气价/轻烃价差、扩产消化、碳排放、能耗双控和安全环保风险",
        },
        "sources": [
            {"id": "BF1", "title": "宝丰能源2025年年度报告业绩报道", "publisher": "新浪财经", "date": "2026-03", "url": "https://finance.sina.com.cn/stock/bxjj/2026-03-12/doc-inhqtuse4677330.shtml", "purpose": "宝丰能源财务和项目线索"},
            {"id": "BF2", "title": "宝丰能源年度发展报道", "publisher": "新浪财经/行业资讯", "date": "2026-03", "url": "https://finance.sina.com.cn/wm/2026-03-17/doc-inhrhpmw3962205.shtml", "purpose": "内蒙古烯烃项目和扩产线索"},
            {"id": "WX1", "title": "卫星化学2025年经营报道", "publisher": "新浪财经/慧正资讯", "date": "2026-03", "url": "https://finance.sina.com.cn/wm/2026-03-26/doc-inhshxnu0274672.shtml", "purpose": "卫星化学营收、基地和产品"},
            {"id": "WX2", "title": "卫星化学2025年ESG报告信息", "publisher": "中财网", "date": "2026-04", "url": "https://www.cfi.net.cn/p20260413001870.html", "purpose": "ESG和绿色发展线索"},
        ],
    },
    "华锦阿美": {
        "aliases": ["华锦阿美", "huajin aramco", "hapco", "盘锦阿美"],
        "profile": {
            "short_name": "华锦阿美",
            "account_type": "中沙合资在建炼化一体化KA",
            "relationship": "国家重点工程和沙特在华最大投资项目，建设期转运营期机会密集",
            "opportunity_level": "高",
            "risk_level": "中高",
            "recommended_focus": "建设转运营期电气系统验收、备件、MCC/低压配电、能源管理和数字化运维",
        },
        "facts": {
            "entity": "华锦阿美石油化工有限公司",
            "nature": "北方华锦、沙特阿美、盘锦鑫诚等合资重大炼化项目公司",
            "ownership": "公开资料显示北方华锦/阿美/盘锦地方平台合资，具体股权以工商和项目公司资料为准",
            "business": "炼油、乙烯、精细化工和下游高端材料一体化",
            "products": "炼油产品、乙烯、PE、PP、ABS、丁二烯、PX、乙二醇等",
            "scale": "总投资约837亿元，1500万吨/年炼油、165万吨/年乙烯及32套主要生产装置",
            "finance": "项目建设期单体经营财务未公开，建成投产后预计年销售收入超过1000亿元",
            "projects": "辽宁盘锦精细化工及原料工程，2025-2026年陆续机械竣工/中交并冲刺投产",
            "market": "东北及环渤海炼化、精细化工、高端材料和中沙能源化工合作链条",
            "strategy": "服务东北振兴、中沙战略合作和高端精细化工基地建设",
            "digital": "智慧工地、项目集成平台、5G网络、监控和人员车辆定位等建设期数字化已上线",
            "green": "国家重点工程，对安全环保、能耗、碳排和装置开车可靠性要求高",
            "risk": "建设转运营、装置中交/开车、国际合资决策链、工程交付、安环合规和资金进度风险",
        },
        "sources": [
            {"id": "HA1", "title": "华锦阿美项目机械竣工进展", "publisher": "盘锦市人民政府", "date": "2025-10-03", "url": "https://www.panjin.gov.cn/html/3060/2025-10-03/content-148152.html", "purpose": "装置竣工进度和建设状态"},
            {"id": "HA2", "title": "华锦阿美项目最大单体设备吊装成功", "publisher": "盘锦市人民政府", "date": "2025-02-27", "url": "https://www.panjin.gov.cn/html/2535/2025-02-27/content-144241.html", "purpose": "投资、炼油乙烯规模和装置数"},
            {"id": "HA3", "title": "华锦阿美项目取得重要进展", "publisher": "中国政府网", "date": "2025-02", "url": "https://www.gov.cn/yaowen/tupian/202502/content_7006401.htm", "purpose": "国家级权威项目进展"},
            {"id": "HA4", "title": "兵器工业集团推进华锦阿美项目", "publisher": "国务院国资委", "date": "2025", "url": "https://wap.sasac.gov.cn/n2588025/n13790238/n16406218/c33175878/content.html", "purpose": "央企侧项目定位和东北振兴"},
        ],
    },
}


PETROCHEM_PUBLIC_DETAILS: dict[str, dict[str, Any]] = {
    "中国石化": {
        "source_ids": ["SP1", "SP2", "SP3"],
        "business_products": "油气、炼油、成品油营销、化工和新材料一体化；2025年加工原油约2.5亿吨、生产成品油约1.49亿吨、乙烯产量约1528万吨，化工产品销量约8712万吨，PX产量创新高，POE等新材料加快发展。",
        "business_revenue": "2025年营业收入约2.78万亿元，经营现金流约1625亿元；炼油收益改善，化工板块因基础石化原料供给增加和毛利下行仍承压。",
        "business_technology": "持续推进油转化、油转特、绿色低碳工艺、新能源新材料和化工高端化，适合围绕关键装置可靠供电、能效和智能化运维切入。",
        "business_projects": "重点基地包括镇海、茂名、齐鲁、九江、上海石化、扬子等炼化/化工基地，化工销售体系覆盖下游工业客户。",
        "procurement_mode": "终端业主型采购，重点应核验集团/炼化企业/项目公司/EPC/成套厂多路径供货，公开资料不能直接判断施耐德合作模式。",
        "procurement_products": "潜在采购品类包括中低压配电、MCC、变频、软启动、保护、电能质量、配电监控、能源管理和检维修备件。",
        "competitors": "竞品生态预计包括ABB、西门子、伊顿、罗克韦尔、国产低压/中压品牌及中石化体系工程公司/EPC指定供应商。",
        "resources": "下游客户覆盖交通燃料、工业化工品、聚合物、新材料、新能源和全国销售网络，化工销售平台是客户结构的重要入口。",
        "sales_market": "全国性炼化和销售网络，成品油需求结构变化推动炼化产品结构优化，化工材料面向工业客户和新材料市场。",
        "org_chain": "集团/上市公司总部、炼化基地、化工销售、工程建设、设备/电仪、采购和安环能源部门共同影响电气采购。",
        "decision_factors": "安全连续生产、业主品牌库、EPC规范、既有装机、供应稳定、价格、检维修响应和低碳节能价值共同影响选型。",
        "strategy": "实施创新驱动、转型升级、资源保障、市场开拓、成本领先、开放合作，构建“一基两翼三链四新”产业格局。",
        "digital": "大型炼化基地具备智能工厂、装置优化、经营数字化和AI应用场景；公开资料难以逐厂确认系统清单。",
        "green": "可持续发展资料披露降碳、减污、提效、增绿、碳达峰行动、CO2回收和甲烷回收，炼化能效提升空间明确。",
        "electrical_needs": "炼化装置、公辅、储运、码头、变电所和老旧装置改造带来高可靠配电、能效管理和EcoFit升级需求。",
        "pain_business": "成品油消费结构变化、化工产能过剩和毛利下行，使炼化企业更关注装置效率、能耗、非计划停机和现金流。",
        "pain_technical": "炼化装置连续生产和高危工艺要求电气系统具备高可靠、可监测、可追溯和快速恢复能力。",
        "pain_market": "新能源汽车渗透、基础化工供给增加和高端材料竞争升级，倒逼油转化、油转特和高端材料布局。",
        "risk_finance": "整体现金流较稳，但化工板块亏损扩大、炼油和营销承压，需关注项目投资节奏和回款条件。",
        "risk_stability": "油价波动、成品油需求、化工周期、安全环保和大型基地连续生产是经营稳定性的核心风险。",
    },
    "中国石油": {
        "source_ids": ["CNPC1", "CNPC2", "CNPC3"],
        "business_products": "油气勘探开发、炼油化工、新材料、销售、天然气和新能源并行；2025年加工原油约13.76亿桶、生产成品油约1.17亿吨，化工商品量约4002.7万吨、化工新材料产量约332.7万吨。",
        "business_revenue": "2025年营业收入约2.86万亿元、归母净利润约1573亿元，油气产量创新高，炼油化工和新材料稳中有进。",
        "business_technology": "油气田、炼化、新材料、新能源、CCUS和数字化油田均有技术升级需求，电气侧适合从站场、炼化和新能源融合场景进入。",
        "business_projects": "长庆、塔里木、大庆、西南等油气田，广东石化、云南石化、吉林石化等炼化与转型项目是重点场景。",
        "procurement_mode": "集团统筹、专业公司/炼化基地/EPC/站场项目多层采购；公开资料不能确认施耐德合作模式和历史采购额。",
        "procurement_products": "潜在品类包括油气田站场配电、炼化MCC、变频软启、低压电器、能源管理、配电监控和新能源场站电气包。",
        "competitors": "主要竞品可能包括ABB、西门子、伊顿、罗克韦尔、国产中低压品牌、油气田电气集成商和集团工程体系供应商。",
        "resources": "面向油气供应、成品油零售、天然气城市燃气/工业客户、化工材料、新能源和地热供暖市场。",
        "sales_market": "油气、天然气、成品油和化工销售网络全国覆盖，新能源发电、地热和CCUS成为增长型业务触点。",
        "org_chain": "总部/专业公司、炼化企业、油气田公司、销售公司、工程建设/EPC、采购、设备、电仪和安环部门共同决策。",
        "decision_factors": "保供安全、站场连续运行、炼化装置可靠性、集团准入、项目规范、价格交期和售后服务是核心因素。",
        "strategy": "增储上产、炼化转型升级、天然气和新能源协同发展，推进油气热电氢综合能源平台。",
        "digital": "油气田、管网、炼化和销售场景均存在数字化资产管理、能源可视化和智能运维需求。",
        "green": "CSR披露2026-2035年继续发展新能源、清洁替代、CCS/CCUS和氢能，2025年新能源发电量同比高增。",
        "electrical_needs": "油气田站场、炼化基地、新能源项目、地热和管网设施需要安全可靠供电、能效管理和远程运维。",
        "pain_business": "油价波动、天然气保供、炼化毛利和大型工程项目交付会放大电气系统稳定性要求。",
        "pain_technical": "油气田和炼化站场分散，远程运维、故障预测、备件响应和低碳用能的技术复杂度高。",
        "pain_market": "能源结构调整要求油气业务与新能源、新材料、天然气和CCUS协同，传统油品增长空间受限。",
        "risk_finance": "盈利稳健但受油价和炼化周期影响，项目资本开支、账期和工程交付仍需按主体核验。",
        "risk_stability": "油气保供、安全环保、管网/站场可靠性、项目施工和炼化装置连续生产是关键风险。",
    },
    "中国海油/中海壳牌": {
        "source_ids": ["CNOOC1", "CNOOC2", "CSPC1", "CSPC2"],
        "business_products": "中国海油以海上油气为主；中海壳牌一期、二期商业运行后乙烯年产能约220万吨、年供应高品质化工产品600多万吨，三期规划160万吨/年乙烯及下游装置。",
        "business_revenue": "中国海油2025年公开报道显示营收约3982亿元、归母净利润约1221亿元；中海壳牌项目公司财务需补充工商/访谈资料。",
        "business_technology": "海上平台、惠州大亚湾化工综合体、聚碳酸酯、线性α烯烃和高端新材料项目对高可靠供电、联锁和电气安全要求高。",
        "business_projects": "中海壳牌惠州三期乙烯项目建设160万吨/年乙烯裂解装置及下游等16套装置，计划2028年建成投产；聚碳酸酯项目同步推进。",
        "procurement_mode": "CNOOC集团、合资公司、Shell/CNOOC股东方、项目管理团队、EPC和承包商共同影响采购，需拆分项目公司和基地口径。",
        "procurement_products": "新建三期项目、电气间、MCC、低压柜、变频、仪表供电、能源管理、备件和开车服务是重点机会。",
        "competitors": "国际化工项目常见ABB、西门子、施耐德、伊顿、罗克韦尔、霍尼韦尔及本地成套/EPC供应商竞争。",
        "resources": "化工产品服务华南及国内高端材料市场，聚碳酸酯、锂电池溶剂和工程塑料带来下游新能源/汽车/电子客户。",
        "sales_market": "惠州大亚湾是华南石化高地，中海壳牌深耕大亚湾并吸引上下游配套企业集聚。",
        "org_chain": "合资公司治理、CNOOC/Shell股东方、惠州基地项目团队、EPC、采购、技术、电仪、安环和生产部门共同决策。",
        "decision_factors": "国际标准、Shell/CNOOC技术规范、项目工期、开车风险、安环合规、本地服务和全生命周期成本权重高。",
        "strategy": "海上油气增储上产与惠州高端化工扩建并行，三期和聚碳项目体现向高端新材料深化布局。",
        "digital": "海上平台和世界级化工基地适合资产绩效管理、远程监测、配电监控和能源可视化。",
        "green": "中国海油ESG治理和低碳发展持续推进；中海壳牌扩建需满足国际化安全环保和低碳标准。",
        "electrical_needs": "三期建设期转运营期将集中出现电气系统验收、调试、备件、开车保障和智能运维需求。",
        "pain_business": "合资决策链长、项目投资大、建设周期长，开车节点和供应链协调对电气包交付要求高。",
        "pain_technical": "大乙烯和聚碳酸酯装置技术复杂，对供电连续性、MCC可靠性、通信和安环联动要求高。",
        "pain_market": "高端新材料竞争加剧，装置投产后需要快速稳定产能和客户认证。",
        "risk_finance": "中国海油盈利强；中海壳牌三期为大额投资项目，需关注建设资金、银团和投产爬坡。",
        "risk_stability": "海上油气安全、台风环境、合资治理、项目延期、开车和安全环保是主要风险。",
    },
    "巴斯夫湛江": {
        "source_ids": ["BASF1", "BASF2", "BASF3"],
        "business_products": "全球第三大巴斯夫一体化基地，核心为100万吨/年乙烯联合装置，并布局基础化学品、中间体、工程塑料、TPU和特种化学品。",
        "business_revenue": "项目公司单体财务未公开；公开资料确认投资约100亿美元，基地全面启用并服务中国及亚太市场。",
        "business_technology": "乙烯联合装置主压缩机电驱并100%使用可再生能源，基地强调智能化、可持续生产和高标准安环。",
        "business_projects": "湛江一体化基地、乙烯联合装置、工程塑料、TPU、液体散货码头和公辅系统已形成完整一体化场景。",
        "procurement_mode": "外资独资项目，采购受巴斯夫全球标准、中国项目公司、EPC、设备包商和本地运维团队共同影响。",
        "procurement_products": "重点机会包括乙烯及下游装置MCC/低压配电、变频、电能质量、能源管理、数字化配电、备件和服务SLA。",
        "competitors": "国际标准项目常见ABB、西门子、施耐德、伊顿、罗克韦尔、霍尼韦尔及本地EPC/成套承包商竞争。",
        "resources": "产品主要供应中国快速增长市场，覆盖汽车、电子、消费品、包装、工业材料和特种化学品客户。",
        "sales_market": "定位华南和亚太高端化学品供应基地，依托巴斯夫全球客户体系和本地化供应能力。",
        "org_chain": "巴斯夫集团/中国区、湛江基地管理层、项目管理、工艺/设备/电仪、采购、EHS和数字化团队共同决策。",
        "decision_factors": "全球技术标准、EHS、安全联锁、可再生能源用电、供应可靠性、现场服务和合规文件权重高。",
        "strategy": "打造巴斯夫在中国的可持续一体化生产旗舰，强化本地供应、创新和低碳生产。",
        "digital": "新建基地从设计阶段即适合数字化工厂、能源管理、资产健康、预测维护和数据驱动的安环管理。",
        "green": "基地100%采用可再生能源电力，是其可持续生产的重要标签，电气系统需支撑绿电、能效和碳足迹管理。",
        "electrical_needs": "新基地投产爬坡、乙烯核心装置和公辅系统需要可靠配电、备件、调试服务和能源透明化。",
        "pain_business": "新建基地爬坡、进口设备维保、本地供应链和开车稳定性会影响产能释放。",
        "pain_technical": "电驱压缩机、乙烯裂解和下游装置对电能质量、保护配合、MCC和高可靠低压系统依赖强。",
        "pain_market": "高端化工材料需快速通过客户认证并稳定供应，市场价格周期仍会影响爬坡收益。",
        "risk_finance": "单体财务未披露，风险主要来自资本开支、投产爬坡、供应链和化工周期。",
        "risk_stability": "新装置开车、安环合规、可再生能源供电稳定、进口备件和本地服务能力是关键风险。",
    },
    "埃克森美孚惠州": {
        "source_ids": ["XOM1", "XOM2", "XOM3", "XOM4"],
        "business_products": "惠州化工综合体一期包括160万吨/年乙烯裂解，两套合计120万吨/年高性能LLDPE、50万吨/年LDPE和两套合计95万吨/年高性能PP装置。",
        "business_revenue": "项目公司财务未公开；公开资料显示其为埃克森美孚在华大型独资石化综合体，已进入运行阶段。",
        "business_technology": "灵活进料蒸汽裂解、高端聚乙烯/聚丙烯、研发中心和世界级化工综合体标准，适合高可靠电气和数字化运维。",
        "business_projects": "惠州乙烯一期、研发中心、码头储运、公用工程及未来二期/扩建，是大亚湾石化产业高地重点项目。",
        "procurement_mode": "外资独资业主标准、项目公司、EPC、设备包商和大亚湾园区供应链共同作用，需核验品牌库和已装机品牌。",
        "procurement_products": "潜在产品包括低压配电、MCC、变频软启、过程装置电气包、能源管理、预测维护、备件和现场服务。",
        "competitors": "国际项目竞争来自ABB、西门子、施耐德、伊顿、罗克韦尔等，也受EPC惯用品牌和本地服务能力影响。",
        "resources": "产品面向包装、汽车、工业、消费品、卫生和个人护理等高性能聚烯烃应用市场。",
        "sales_market": "定位中国及亚太高性能聚烯烃和高端化工材料供应基地，依托埃克森美孚全球客户网络。",
        "org_chain": "ExxonMobil全球/中国项目管理、惠州基地、工艺设备、电仪、采购、EHS、研发和园区接口共同决策。",
        "decision_factors": "全球标准、安全、开车稳定、装置连续性、备件体系、技术支持、交付确定性和总拥有成本。",
        "strategy": "扩大高价值化工产能和中国本地制造，增强亚太高性能材料供应链。",
        "digital": "新建世界级装置适合资产绩效管理、配电监控、能源管理、远程诊断和可靠性分析。",
        "green": "需满足广东大亚湾高标准安全环保和绿色园区要求，电气能效与碳数据可作为切入点。",
        "electrical_needs": "一期运行爬坡和未来二期/扩建带来电气系统稳定、备件、服务、能效和项目标准化需求。",
        "pain_business": "新装置试生产到稳定商业运行的爬坡、客户认证和本地供应链成熟度是短期痛点。",
        "pain_technical": "高性能聚烯烃装置对MCC、变频、电能质量、保护和供电连续性敏感。",
        "pain_market": "聚烯烃市场竞争和价格周期要求装置稳定运行、差异化产品和成本控制。",
        "risk_finance": "项目单体财务未披露，风险集中在开车爬坡、扩建投资、化工周期和供应链。",
        "risk_stability": "试生产、开车、安环、进口技术备件和二期审批/建设节奏是主要风险。",
    },
    "万华化学": {
        "source_ids": ["WH1", "WH2", "WH3"],
        "business_products": "形成聚氨酯、石化、精细化学品、新兴材料、未来产业五大产业集群，核心产品包括MDI/TDI、多元醇、丙烯酸及酯、聚烯烃和特种化学品。",
        "business_revenue": "2025年营业收入约2032.35亿元、归母净利润约125.27亿元，收入增长但利润承压。",
        "business_technology": "拥有国内外十四大生产基地及工厂、七大研发中心，全球研发和工程化能力强，适合联合高可靠配电和能源管理标准。",
        "business_projects": "烟台、宁波、福建、四川、珠海、宁夏及海外基地持续推进新材料、技改和一体化项目。",
        "procurement_mode": "集团多基地、事业部和项目公司采购并行，需核验万华电仪/设备/采购对施耐德品牌库和EPC规范的使用情况。",
        "procurement_products": "重点机会包括化工基地中低压配电、MCC、变频、电能质量、智能配电、能源管理、备件和服务框架。",
        "competitors": "国际品牌ABB、西门子、伊顿、罗克韦尔和国产中低压品牌均可能参与，多基地标准化对品牌统一有影响。",
        "resources": "下游覆盖建筑、汽车、家电、鞋材、涂料、电子、新能源和高端材料客户，全球化销售服务网络强。",
        "sales_market": "全球聚氨酯和化工新材料龙头，国内外基地支撑全球客户交付。",
        "org_chain": "集团/事业部/基地、项目建设、采购、设备、电仪、研发、EHS和生产运行部门共同影响电气选型。",
        "decision_factors": "安全、质量、工艺连续性、供应稳定、成本、技术标准、全球一致性和项目交付能力共同影响。",
        "strategy": "从化工企业向化工+新能源转型，强化聚氨酯领先、石化一体化和新材料布局。",
        "digital": "多基地连续生产、全球运营和研发制造协同带来MES、DCS、能源管理、配电资产健康和预测维护需求。",
        "green": "重视绿色低碳、质量安全和创新驱动，危化品安全与能耗管理压力高。",
        "electrical_needs": "烟台、宁波、福建等大型基地技改、新材料装置和公辅系统适合高可靠配电与能源管理方案。",
        "pain_business": "化工价格周期和多基地扩张使成本、产能利用率、项目交付和现金流管理重要性提升。",
        "pain_technical": "MDI/TDI和新材料装置对连续供电、电仪联动、备件和检维修窗口要求高。",
        "pain_market": "下游需求波动、国际竞争和新材料客户认证对装置稳定与质量一致性提出要求。",
        "risk_finance": "利润承压、原料价格、化工周期和海外运营风险需关注。",
        "risk_stability": "危化品安全、环保、装置连续运行、多基地项目交付和国际贸易是主要风险。",
    },
    "荣盛石化/浙石化": {
        "source_ids": ["RS1", "RS2", "RS3", "ZPC1"],
        "business_products": "依托浙石化4000万吨/年炼化一体化项目，形成油品、芳烃、烯烃、PTA、聚酯、工程塑料、新能源、高端聚烯烃和特种材料链条。",
        "business_revenue": "2025年营业收入约3086.22亿元、归母净利润约8.48亿元，经营现金流约454.06亿元，研发费用公开报道约49.89亿元。",
        "business_technology": "以科技引领、绿色转型、全球拓展为主线，推进高端化、智能化、绿色化产业链和新材料升级。",
        "business_projects": "舟山绿色石化基地、原油储运码头、聚酯和新材料基地，以及沙特阿美合作和海外炼厂权益布局。",
        "procurement_mode": "超大型民营炼化业主采购，需拆分荣盛上市公司、浙石化、基地项目、EPC和成套承包商供货路径。",
        "procurement_products": "炼化基地低压配电、MCC、变频、电能质量、储运码头、公辅系统、能源管理、备件和检修服务需求明显。",
        "competitors": "国际电气品牌、本地成套厂、EPC惯用供应商和国产低压品牌共同竞争，成本压力强。",
        "resources": "下游覆盖聚酯、化纤、包装、工程塑料、新能源材料、油品和化工品市场。",
        "sales_market": "七大生产基地和浙石化超大炼化平台支撑全球级芳烃、炼化和聚酯供应能力。",
        "org_chain": "荣盛集团/上市公司、浙石化基地、项目建设、采购、设备、电仪、安环、码头储运和销售部门共同决策。",
        "decision_factors": "价差周期、装置连续性、储运安全、项目成本、供货稳定、国产替代和EPC/设计院规范影响选型。",
        "strategy": "从大炼化向高端化、新材料、低碳化和国际化协同升级。",
        "digital": "超大型炼化、储运和码头体系需要统一能源管理、电气资产监控、状态监测和检修数字化。",
        "green": "可持续发展报告披露环境、质量安全、责任采购和绿色低碳，适合以能效和碳数据切入。",
        "electrical_needs": "舟山基地、码头储运、公辅系统和技改项目带来高可靠供电、电能质量和低碳改造需求。",
        "pain_business": "炼化价差、财务费用、短期借款和现金流压力促使客户关注降本增效。",
        "pain_technical": "4000万吨级基地复杂度高，储运/码头/公辅/化工装置接口多，电气可靠性和检修效率是痛点。",
        "pain_market": "炼油向化工材料转型加速，高端聚烯烃、工程塑料和特种材料竞争升级。",
        "risk_finance": "利润较薄、债务和财务费用压力较高，需关注授信、账期和项目付款条件。",
        "risk_stability": "原油价格、炼化价差、资产负债、装置安全、环保和地缘贸易是主要风险。",
    },
    "恒力石化": {
        "source_ids": ["HL1", "HL2", "HL3"],
        "business_products": "覆盖炼化、芳烃、烯烃、PTA、聚酯、新材料、功能性薄膜和化纤产业链，依托大连长兴岛炼化平台。",
        "business_revenue": "2025年营业收入约2010亿元、归母净利润约70.75亿元，炼化产销稳健；公开报道显示研发人员约4348人，占员工比例约11.64%。",
        "business_technology": "推进高附加值技改和精品项目建设，突破高端差别化聚酯、高性能改性聚烯烃等关键技术。",
        "business_projects": "大连炼化一体化基地、PTA、聚酯新材料、科技创新债支持的技改和高端材料项目。",
        "procurement_mode": "大连基地、上市公司、事业部、EPC/设备包和采购系统多层采购，需核验施耐德在炼化与聚酯板块装机基础。",
        "procurement_products": "低压配电、MCC、变频、软启动、电能质量、能源管理、备件、服务和公辅系统改造是重点。",
        "competitors": "国际品牌和国产中低压品牌均会参与，成本、交付、国产化和EPC关系影响较大。",
        "resources": "面向油品、化工品、聚酯、纤维、包装材料、新材料和海外客户。",
        "sales_market": "大化工平台支撑炼化、聚酯和新材料一体化经营，产品覆盖国内外产业链客户。",
        "org_chain": "集团/上市公司、大连基地、炼化/聚酯事业部、采购、设备、电仪、EHS和项目管理部门共同决策。",
        "decision_factors": "大装置成本优势、项目投资、装置稳定、价格、交付、服务响应和政策/合规因素共同影响。",
        "strategy": "深化提质增效，推进高端材料进口替代和炼化新材料协同，强化可持续发展和风险管理。",
        "digital": "炼化和聚酯连续生产适合能源管理、配电监控、设备状态监测和检修数字化。",
        "green": "可持续发展报告披露安全生产、环境保护和ESG管理，节能降耗和环保合规是切入点。",
        "electrical_needs": "大连炼化基地、公辅、电机拖动、MCC室、聚酯项目和技改需要高可靠配电与能效优化。",
        "pain_business": "营收承压、原油/聚酯周期、政策和国际贸易不确定性提高降本增效要求。",
        "pain_technical": "超大型连续生产装置对变频、MCC、电能质量、备件和检修窗口依赖高。",
        "pain_market": "聚酯和炼化景气周期波动，高端材料进口替代要求产品质量稳定和快速研发转产。",
        "risk_finance": "盈利韧性较强但受原油价格、终端需求、汇率、项目建设和外部合规影响。",
        "risk_stability": "炼化安全、环保、贸易合规、项目建设和连续生产是主要风险。",
    },
    "东方盛虹/盛虹炼化": {
        "source_ids": ["SH1", "SH2", "SH3", "SH4", "SH6", "SH7", "SH8", "SH9", "SH10"],
        "business_products": "东方盛虹以石化及化工新材料、聚酯化纤为核心：盛虹炼化1600万吨/年炼化一体化、280万吨/年PX、110万吨/年乙烯；斯尔邦240万吨/年MTO、70万吨/年PDH、104万吨/年丙烯腈、90万吨/年EVA、10万吨/年POE、34万吨/年MMA；聚酯化纤约360万吨/年涤纶长丝和60万吨/年再生聚酯纤维。",
        "business_revenue": "2025年营业收入1,255.87亿元，同比下降8.78%；归母净利润1.34亿元，扣非净利润-5.43亿元；经营性现金流净额160.53亿元；石化及化工新材料收入约994.72亿元，化纤收入约239.57亿元。2026年一季度营业收入320.22亿元、归母净利润14.32亿元、经营性现金流35.34亿元，说明周期底部后盈利和现金流已明显修复，但资产负债率仍约81%，商务授信和付款路径仍需谨慎。",
        "business_technology": "2025年自主研发并上线“盛虹流程工业智能大模型平台”，打通智能体、模型与数据三大软件总线；集团级知识引擎在PDH等核心装置投运，另有智能物料系统、法务智能助手、黑灯实验室、采购系统智能化升级、设备助手等场景；盛虹炼化1600万吨炼化一体化智能工厂和斯尔邦醇基多联产智能工厂获评江苏省先进级智能工厂。",
        "business_projects": "项目经营应拆到基地/装置/包件：盛虹炼化1600万吨/年炼化一体化项目位于连云港徐圩新区，含主体工程、30万吨级原油泊位、液体化工泊位、储运、公辅和环保工程；斯尔邦MTO/PDH/EVA/POE/丙烯腈为新能源材料平台；虹港PTA、虹威POSM及多元醇、石化港储和聚酯化纤基地构成持续技改与运维机会。新增检索确认10万吨/年POE工业化装置已投产，光伏胶膜、汽车制造和聚合物改性等高端材料场景会继续拉动稳定供电、洁净生产、能效和质量一致性需求。",
        "procurement_mode": "年报披露原料端按年度/月度采购计划、长约+现货滚动补充；从盘厂KA视角，电气采购需分上市公司、盛虹炼化、斯尔邦、虹港、石化港储、基地项目、EPC/设计院、采购、设备、电仪、安环和生产运行多主体，并核验业主品牌库、项目BOM、合格供应商和历史装机。",
        "procurement_products": "重点机会不是一次性元件销售，而是基地项目制供货：中低压柜、MCC、变频/软启、电能质量、关键负载供配电、UPS/应急电源、智能配电、PME/PO/能源管理、温度/局放/弧光监测、检修备件、开车保运、现场服务SLA和培训。",
        "competitors": "公开资料未披露电气品牌清单；按大型炼化项目常见竞争格局，ABB、西门子、施耐德、伊顿、国产中低压品牌、DCS/仪表包商、EPC惯用品牌和连云港/江苏本地成套厂均可能进入。需用项目BOM、技术协议和柜内照片核验实际装机。",
        "resources": "下游客户资源覆盖光伏胶膜、碳纤维、化纤纺织、包装、能源燃料、工业材料和海外市场；年报披露斯尔邦光伏级EVA覆盖国内众多光伏胶膜头部企业，丙烯腈成为国内众多主流碳纤维企业主要原料供应商，聚酯产品外销40余个国家和地区；POE投产进一步加强其在光伏胶膜高端原料上的客户牵引。",
        "sales_market": "销售以直销为主，面向大型客户和优质客户直接对接；化纤外销覆盖韩国、土耳其、越南、巴基斯坦、意大利等40余个国家和地区；重要客户存在长期框架合同，内销多采用款到发货，少量信用良好客户给予账期。",
        "org_chain": "实际控制人缪汉根、朱红梅夫妇；缪汉根任董事长、总经理，杨天威、计高雄、王俊、胡贵洋等构成上市公司经营/财务/董秘线索。盘厂KA成交更关键的是盛虹炼化/斯尔邦/虹港基地总经理、项目建设、采购、设备、电仪、安环、生产运行、EPC/设计院和盘厂承包商。",
        "decision_factors": "电气选型应按安全环保、连续生产、开车/检修窗口、能耗优化、业主/EPC标准、历史装机、备件响应、项目成本、付款信用和现金流约束共同判断；对关键装置要避免只做价格比较。",
        "strategy": "公司以“1+N”产业格局为主线，围绕新能源材料、高性能新材料、低碳绿色产业发展；2026年计划深化AI融合，在智能工厂、业财分析、大宗商品/衍生品交易、生产制造、安全、设备预测性维护和质量预测等场景推进智能体应用。POE工业化、先进材料研究院和中试平台线索表明其战略正在从炼化规模平台转向高端材料放量与数智化运营。",
        "digital": "东方盛虹已经把AI、智能工厂和采购系统智能化作为经营抓手，已上线盛虹流程工业智能大模型平台并推进装置操作导航、智能物料、设备助手等场景；对施耐德而言，智能配电、电力监控、能效管理、资产健康、预测维护和电气数据接入客户工业大模型，是比单纯供柜更高价值的入口。",
        "green": "官网和年报披露其建成全球首条二氧化碳到聚酯纤维产业链、废弃矿泉水瓶到聚酯纤维绿色链条；盛虹炼化、斯尔邦、虹港等绿色工厂线索突出，安全环保、能效、碳数据和绿色产品是持续经营约束。",
        "electrical_needs": "连云港炼化及斯尔邦装置、虹港PTA、石化港储、公辅变电所、MCC室、PDH/MTO/EVA/POE/丙烯腈、POSM及多元醇项目均适合智能配电、能效管理、电能质量、备件框架、检修服务和电气资产健康切入。POE等高端材料装置对连续稳定、洁净生产、质量一致性和检修窗口更敏感，可作为施耐德智能配电和电气资产健康试点场景。",
        "pain_business": "业务痛点应拆成四类举证：营收和扣非利润承压带来的降本增效压力；1600万吨炼化和多套新材料装置连续生产带来的停机/稳质风险；长约+现货、EPC/设计院/盘厂多接口带来的供应链协同压力；AI、HSE和预测维护推进带来的复合型电仪/数字化人才压力。",
        "pain_business_efficiency": "生产效率痛点：2025年营业收入1,255.87亿元，同比下降8.78%，扣非净利润-5.43亿元；2026年一季度净利润和经营现金流显著修复，说明降本增效和价差改善已经进入管理重点。年报说明石化行业供需两端面临挑战、原油价格宽幅震荡且部分下游需求阶段性承压，公司已把技改、检修、优化装置运行、降低能耗及生产成本作为应对动作。对施耐德盘厂KA的含义是：不要只谈供柜价格，要用关键负载停机损失、MCC/变频效率、能耗可视化和检修窗口响应证明降本增效。",
        "pain_business_quality": "质量管控痛点：官网披露盛虹炼化项目为1600万吨/年炼油、280万吨/年PX、110万吨/年乙烯，并配套30万吨原油码头、4个5万吨液体化工码头和425万立方仓储；年报还提示EVA新装置从开车成功到连续规模化稳质稳产需一定周期。装置规模大、产品链长、开车爬坡和稳质稳产并行，使供配电连续性、MCC可靠性、保护整定、FAT/SAT和备件响应成为质量稳定的底层约束。",
        "pain_business_supply_chain": "供应链痛点：年报披露原料采购按年度/月度计划，以长约和现货滚动补充来控制成本，前五大供应商采购额占年度采购总额39.77%；横河公开资料显示其为盛虹炼化项目提供DCS、OTS、PID性能评估和变送器等自动化方案。对电气侧而言，痛点不是单一采购，而是业主、EPC、设计院、自动化包商、盘厂和运维团队之间的品牌库、BOM、交期、备件和数据接口协同。",
        "pain_business_talent": "人才与组织痛点：年报披露公司已上线流程工业智能大模型平台，并计划在安全、生产、设备预测性维护、质量预测等场景推进智能体；同一报告也提示危险化学品生产存储面临人员失误、设备故障等安全环保风险。东方盛虹需要的不只是传统电气维护人员，而是懂电仪、配电数据、HSE、能效和AI场景的复合型团队，适合用施耐德培训、联合诊断和样板间降低落地风险。",
        "pain_technical": "1600万吨级炼化、MTO、PDH、EVA、POE、丙烯腈、PTA和聚酯化纤连续生产装置接口复杂，对供电连续性、MCC可靠性、电能质量、保护整定、备件响应和智能运维要求高。",
        "pain_market": "EVA、POE、丙烯腈、聚酯化纤和炼化产品受周期、原料和需求影响；2026年品牌价值报告提到东方盛虹品牌价值增长受需求疲弱和价格压力约束。客户需要用高端化、绿色化、数智化和成本优化提升抗周期能力。",
        "risk_finance": "2025年末总资产2,052.28亿元、负债1,670.20亿元，资产负债率约81.38%；2026年一季度总资产约2,103.59亿元，归母净资产约356.42亿元，盈利修复但杠杆仍高。短期借款493.54亿元、长期借款584.11亿元，全部担保余额占公司净资产445.99%，需重点核验授信、账期和项目付款风险。",
        "risk_stability": "主要风险包括宏观经济波动、政策与安全环保监管、汇率、原油/甲醇/丙烷和产品价格波动、连续生产安全、环保突发事件、设备故障和大型项目开车/检修风险。",
    },
    "宝丰能源/卫星化学": {
        "source_ids": ["BF1", "BF2", "WX1", "WX2"],
        "business_products": "宝丰能源以煤制烯烃、焦化、甲醇、精细化工和新能源协同为主；卫星化学以C2/C3轻烃化工、丙烯酸及酯、高分子材料和新材料为主。",
        "business_revenue": "宝丰能源2025年营收约480.38亿元、归母净利润约113.50亿元；卫星化学2025年营收超460亿元，境外收入增速较快。",
        "business_technology": "宝丰内蒙古300万吨/年煤制烯烃项目投产，2025年末烯烃产能约520万吨/年；卫星嘉兴9万吨丙烯酸投产，连云港乙烯装置检修优化。",
        "business_projects": "宝丰宁东/内蒙古煤制烯烃、宁东四期；卫星嘉兴丙烯酸和连云港轻烃一体化项目。",
        "procurement_mode": "两家公司主体不同，需分别建立客户编码、采购主体、基地、EPC和成套厂关系，避免混用。",
        "procurement_products": "煤化工/轻烃化工基地低压配电、MCC、变频、软启动、电能质量、能源管理和扩产项目电气包为重点。",
        "competitors": "国产低压品牌、国际品牌、煤化工/轻烃EPC供应链和本地成套厂共同竞争，成本敏感度较高。",
        "resources": "宝丰面向聚烯烃、焦化和精细化工客户；卫星面向丙烯酸、包装、涂料、胶粘剂、卫生用品和高分子材料客户。",
        "sales_market": "宝丰依托煤制烯烃成本优势扩大规模，卫星依托轻烃路线和海外市场增长提升竞争力。",
        "org_chain": "宝丰和卫星需分别识别集团/上市公司、基地、项目、采购、设备、电仪、安环、能源管理和生产负责人。",
        "decision_factors": "成本优势、扩产进度、能耗碳排、安全环保、装置稳定和价格交期共同影响电气选型。",
        "strategy": "宝丰推进煤基新材料循环经济和新能源协同；卫星推进轻烃一体化、高端材料和海外增长。",
        "digital": "连续生产和扩产项目带来能源管理、配电监测、资产健康、煤化工/轻烃装置数据联动需求。",
        "green": "宝丰强调煤炭清洁高效利用和新能源，卫星披露ESG并推进绿色化工，碳排和能耗约束突出。",
        "electrical_needs": "内蒙古、宁东、嘉兴、连云港基地扩产和检修为智能配电、能效和备件服务提供机会。",
        "pain_business": "煤价、轻烃价差、聚烯烃/丙烯酸价格和扩产消化影响盈利稳定性。",
        "pain_technical": "煤化工高耗能、轻烃装置连续运行、MCC/变频和电能质量对生产稳定影响大。",
        "pain_market": "聚烯烃和丙烯酸产品价格下行时，成本优势与高端牌号开发成为核心。",
        "risk_finance": "宝丰利润强但受煤化工周期和碳约束影响；卫星受轻烃价差、海外市场和产品价格波动影响。",
        "risk_stability": "安全环保、能耗双控、碳排、扩产爬坡和产品价格是主要风险。",
    },
    "华锦阿美": {
        "source_ids": ["HA1", "HA2", "HA3", "HA4"],
        "business_products": "规划1500万吨/年炼油、165万吨/年乙烯和32套主要生产装置，产品包括炼油、PE、PP、ABS、丁二烯、PX、乙二醇等。",
        "business_revenue": "建设期单体经营财务未公开；总投资约837亿元，建成后公开资料预计年销售收入超过1000亿元。",
        "business_technology": "国家重点工程和中沙合资项目，建设期已上线智慧工地、集成平台、5G、监控和人员车辆定位等数字化手段。",
        "business_projects": "辽宁盘锦精细化工及原料工程，2025-2026年装置机械竣工/中交/投产冲刺。",
        "procurement_mode": "北方华锦、沙特阿美、盘锦地方平台、项目公司、EPC总包和施工单位共同影响采购，建设期和运营期路径不同。",
        "procurement_products": "建设转运营期重点机会包括低压配电、MCC、变频、开车备件、调试服务、能源管理、数字化运维和现场服务SLA。",
        "competitors": "国际电气品牌、工程公司绑定供应商、国产中低压品牌和盘锦/东北本地成套服务商竞争。",
        "resources": "项目服务东北及环渤海炼化、精细化工、高端材料和中沙能源化工合作链条。",
        "sales_market": "定位国家重点工程、东北振兴和中沙高端精细化工合作平台，投产后将形成千亿级销售规模。",
        "org_chain": "股东方治理、项目公司、EPC总包、施工/监理、设备、电仪、采购、安环和未来生产运行团队共同决策。",
        "decision_factors": "工程节点、机械竣工/中交/开车、安全环保、国际合资标准、供应商履约和现场服务能力权重高。",
        "strategy": "服务东北振兴、中沙战略合作和高端精细化工基地建设，从建设期转向运营期开车保障。",
        "digital": "智慧工地、5G网络、项目集成平台和现场监控为后续数字化运维、电气资产管理打基础。",
        "green": "国家重点炼化项目对安环、能耗、碳排和装置开车可靠性要求高。",
        "electrical_needs": "投产前后将集中出现电气系统验收、试运行、备件建库、培训、MCC/低压配电和能源管理需求。",
        "pain_business": "建设转运营、节点密集、国际合资沟通和多承包商接口会放大交付和开车风险。",
        "pain_technical": "大型炼油乙烯装置初次开车对供电连续性、保护整定、MCC和备件响应要求极高。",
        "pain_market": "投产后需面对炼化周期和高端材料市场竞争，建设期则重在按期高质量投产。",
        "risk_finance": "建设期经营现金流未公开，风险集中在投资进度、资金安排、工程变更和投产爬坡。",
        "risk_stability": "装置中交/开车、工程交付、安全环保、国际合资决策和资金进度是主要风险。",
    },
}


for _name, _details in PETROCHEM_PUBLIC_DETAILS.items():
    if _name in PETROCHEM_KA_DATA:
        PETROCHEM_KA_DATA[_name]["public_details"] = _details


def find_petrochem_ka(customer: str) -> dict[str, Any] | None:
    normalized = customer.replace("（", "(").replace("）", ")").lower()
    for name, data in PETROCHEM_KA_DATA.items():
        aliases = [name, *data.get("aliases", [])]
        if any(str(alias).lower() in normalized for alias in aliases):
            return data | {"name": name}
    return None
